# generated by cabal-rpm-2.0.7 --standalone --stream hackage
# https://docs.fedoraproject.org/en-US/packaging-guidelines/Haskell/

%global ghc_without_dynamic 1
%global ghc_without_shared 1
%undefine with_ghc_prof
%undefine with_haddock
%global without_prof 1
%global without_haddock 1
%global debug_package %{nil}

%global pkg_name dhall
%global pkgver %{pkg_name}-%{version}

# testsuite missing deps: generic-random quickcheck-instances special-values spoon tasty-expected-failure tasty-silver

Name:           %{pkg_name}
Version:        1.35.0
Release:        1%{?dist}
Summary:        A configuration language guaranteed to terminate

License:        BSD
Url:            https://hackage.haskell.org/package/%{name}
# Begin cabal-rpm sources:
Source0:        https://hackage.haskell.org/package/%{pkgver}/%{pkgver}.tar.gz
Source1:        https://hackage.haskell.org/package/%{pkgver}/%{name}.cabal#/%{pkgver}.cabal
# End cabal-rpm sources

# Begin cabal-rpm deps:
BuildRequires:  ghc-Cabal-devel
BuildRequires:  ghc-rpm-macros
BuildRequires:  ghc-Diff-devel
BuildRequires:  ghc-aeson-devel
BuildRequires:  ghc-aeson-pretty-devel
BuildRequires:  ghc-ansi-terminal-devel
%if 0%{?fedora} >= 32
BuildRequires:  ghc-atomic-write-devel
%endif
BuildRequires:  ghc-base-devel
BuildRequires:  ghc-bytestring-devel
BuildRequires:  ghc-case-insensitive-devel
%if 0%{?fedora} >= 32
BuildRequires:  ghc-cborg-devel
BuildRequires:  ghc-cborg-json-devel
%endif
BuildRequires:  ghc-containers-devel
BuildRequires:  ghc-contravariant-devel
BuildRequires:  ghc-cryptonite-devel
%if 0%{?fedora} >= 32
BuildRequires:  ghc-data-fix-devel
%endif
BuildRequires:  ghc-deepseq-devel
BuildRequires:  ghc-directory-devel
BuildRequires:  ghc-dotgen-devel
BuildRequires:  ghc-either-devel
BuildRequires:  ghc-exceptions-devel
BuildRequires:  ghc-filepath-devel
BuildRequires:  ghc-half-devel
BuildRequires:  ghc-hashable-devel
BuildRequires:  ghc-haskeline-devel
BuildRequires:  ghc-http-client-devel
BuildRequires:  ghc-http-client-tls-devel
BuildRequires:  ghc-http-types-devel
BuildRequires:  ghc-lens-family-core-devel
BuildRequires:  ghc-megaparsec-devel
BuildRequires:  ghc-memory-devel
BuildRequires:  ghc-mmorph-devel
BuildRequires:  ghc-mtl-devel
BuildRequires:  ghc-network-uri-devel
BuildRequires:  ghc-optparse-applicative-devel
BuildRequires:  ghc-parser-combinators-devel
%if 0%{?fedora} >= 32
BuildRequires:  ghc-parsers-devel
BuildRequires:  ghc-pretty-simple-devel
%endif
BuildRequires:  ghc-prettyprinter-devel
BuildRequires:  ghc-prettyprinter-ansi-terminal-devel
BuildRequires:  ghc-profunctors-devel
BuildRequires:  ghc-repline-devel
BuildRequires:  ghc-scientific-devel
%if 0%{?fedora} >= 32
BuildRequires:  ghc-serialise-devel
%endif
BuildRequires:  ghc-template-haskell-devel
BuildRequires:  ghc-text-devel
%if 0%{?fedora} >= 32
BuildRequires:  ghc-text-manipulate-devel
%endif
BuildRequires:  ghc-th-lift-instances-devel
BuildRequires:  ghc-transformers-devel
BuildRequires:  ghc-transformers-compat-devel
BuildRequires:  ghc-unordered-containers-devel
BuildRequires:  ghc-uri-encode-devel
BuildRequires:  ghc-vector-devel
BuildRequires:  cabal-install > 1.18
%if 0%{?fedora} < 32
# for missing dep 'atomic-write':
BuildRequires:  ghc-temporary-devel
BuildRequires:  ghc-unix-compat-devel
# for missing dep 'cborg':
BuildRequires:  ghc-array-devel
BuildRequires:  ghc-primitive-devel
# for missing dep 'parsers':
BuildRequires:  ghc-attoparsec-devel
BuildRequires:  ghc-base-orphans-devel
BuildRequires:  ghc-binary-devel
BuildRequires:  ghc-charset-devel
BuildRequires:  ghc-parsec-devel
BuildRequires:  ghc-semigroups-devel
# for missing dep 'serialise':
BuildRequires:  ghc-array-devel
BuildRequires:  ghc-primitive-devel
BuildRequires:  ghc-time-devel
%endif

%description
Dhall is an explicitly typed configuration language that is not Turing
complete. Despite being Turing incomplete, Dhall is a real programming language
with a type-checker and evaluator.


%prep
# Begin cabal-rpm setup:
%setup -q
cp -bp %{SOURCE1} %{name}.cabal
# End cabal-rpm setup


%build
# Begin cabal-rpm build:
cabal update
%if 0%{fedora} < 33
cabal sandbox init
cabal install
%endif
# End cabal-rpm build


%install
mkdir -p %{buildroot}%{_bindir}
%if 0%{fedora} >= 33
cabal install --install-method=copy --installdir=%{buildroot}%{_bindir}
%else
strip -s -o %{buildroot}%{_bindir}/dhall .cabal-sandbox/bin/dhall
%endif
# Begin cabal-rpm install
mkdir -p %{buildroot}%{_datadir}/bash-completion/completions/
%{buildroot}%{_bindir}/%{name} --bash-completion-script %{name} > %{buildroot}%{_datadir}/bash-completion/completions/%{name}
# End cabal-rpm install
mkdir -p %{buildroot}%{_datadir}/%{pkgver}
cp -pr dhall-lang/Prelude %{buildroot}%{_datadir}/%{pkgver}


%files
# Begin cabal-rpm files:
%license LICENSE
%doc CHANGELOG.md
%{_bindir}/%{name}
%{_datadir}/%{pkgver}
%{_datadir}/bash-completion/completions/%{name}
# End cabal-rpm files


%changelog
* Tue Oct  6 15:41:19 +08 2020 Jens Petersen <petersen@redhat.com> - 1.35.0-1
- update to 1.35.0

* Sat Feb  8 2020 Jens Petersen <petersen@redhat.com> - 1.29.0-2
- update deps and add dhall-yaml

* Fri Feb  7 2020 Tristan Cacqueray <tdecacqu@redhat.com> - 1.29.0-1
- bump dhall-json to 1.6.1 and add json-to-dhall cli

* Wed Feb  5 2020 Jens Petersen <petersen@redhat.com> - 1.19.1-2
- add dhall-json 1.2.6

* Tue Jan 28 2020 Fedora Haskell SIG <haskell@lists.fedoraproject.org> - 1.19.1-1
- spec file generated by cabal-rpm-2.0.0
