# generated by cabal-rpm-2.0.2 --standalone
# https://fedoraproject.org/wiki/Packaging:Haskell

%global ghc_without_dynamic 1
%global ghc_without_shared 1
%undefine with_ghc_prof
%undefine with_haddock
%global debug_package %{nil}

%global pkg_name dhall-json
%global pkgver %{pkg_name}-%{version}

Name:           %{pkg_name}
Version:        1.2.6
Release:        1%{?dist}
Summary:        Compile Dhall to JSON or YAML

License:        BSD
Url:            https://hackage.haskell.org/package/%{name}
# Begin cabal-rpm sources:
Source0:        https://hackage.haskell.org/package/%{pkgver}/%{pkgver}.tar.gz
Source1:        https://hackage.haskell.org/package/%{pkgver}/%{name}.cabal#/%{pkgver}.cabal
# End cabal-rpm sources

# Begin cabal-rpm deps:
BuildRequires:  ghc-Cabal-devel
BuildRequires:  ghc-rpm-macros
BuildRequires:  ghc-aeson-devel
BuildRequires:  ghc-aeson-pretty-devel
BuildRequires:  ghc-base-devel
BuildRequires:  ghc-bytestring-devel
#BuildRequires:  ghc-dhall-devel
BuildRequires:  ghc-optparse-applicative-devel
BuildRequires:  ghc-text-devel
BuildRequires:  ghc-unordered-containers-devel
BuildRequires:  ghc-vector-devel
BuildRequires:  ghc-yaml-devel
BuildRequires:  cabal-install > 1.18
# for missing dep 'dhall':
BuildRequires:  ghc-Diff-devel
BuildRequires:  ghc-ansi-terminal-devel
BuildRequires:  ghc-case-insensitive-devel
BuildRequires:  ghc-cborg-devel
BuildRequires:  ghc-containers-devel
BuildRequires:  ghc-contravariant-devel
BuildRequires:  ghc-cryptonite-devel
BuildRequires:  ghc-directory-devel
BuildRequires:  ghc-dotgen-devel
BuildRequires:  ghc-exceptions-devel
BuildRequires:  ghc-filepath-devel
BuildRequires:  ghc-haskeline-devel
BuildRequires:  ghc-http-client-devel
BuildRequires:  ghc-http-client-tls-devel
BuildRequires:  ghc-http-types-devel
BuildRequires:  ghc-lens-family-core-devel
BuildRequires:  ghc-megaparsec-devel
BuildRequires:  ghc-memory-devel
BuildRequires:  ghc-mtl-devel
BuildRequires:  ghc-parsers-devel
BuildRequires:  ghc-prettyprinter-devel
BuildRequires:  ghc-prettyprinter-ansi-terminal-devel
BuildRequires:  ghc-repline-devel
BuildRequires:  ghc-scientific-devel
BuildRequires:  ghc-serialise-devel
BuildRequires:  ghc-template-haskell-devel
BuildRequires:  ghc-transformers-devel
BuildRequires:  ghc-uri-encode-devel
# End cabal-rpm deps

%description
Use this package if you want to compile Dhall expressions to JSON or YAML.
You can use this package as a library or an executable:

* See the "Dhall.JSON" module if you want to use this package as a library

* Use the 'dhall-to-json' or 'dhall-to-yaml' programs from this package if you
want an executable

The "Dhall.JSON" module also contains instructions for how to use this package.


%prep
# Begin cabal-rpm setup:
%setup -q
cp -bp %{SOURCE1} %{name}.cabal
# End cabal-rpm setup


%build
# Begin cabal-rpm build:
%global cabal cabal
%cabal update
%cabal sandbox init
%cabal install --only-dependencies
%ghc_bin_build
# End cabal-rpm build


%install
# Begin cabal-rpm install
%ghc_bin_install
find %{buildroot}%{_libdir} -name 'libHS%{pkgver}-*.so' -delete
rm -r %{buildroot}%{ghclibdir}
# End cabal-rpm install


%files
# Begin cabal-rpm files:
%license LICENSE
%doc CHANGELOG.md
%{_bindir}/dhall-to-json
%{_bindir}/dhall-to-yaml
# End cabal-rpm files


%changelog
* Sat Feb  8 2020 Fedora Haskell SIG <haskell@lists.fedoraproject.org> - 1.2.6-1
- spec file generated by cabal-rpm-2.0.2
